### ISSUE TITLE
Great Big `iv` Wish List

### ISSUE THREAD

**Issue by lgritz** [OpenImageIO/oiio#2058]
# Master list of `iv` feature requests

Rather than proliferate scattered issues, let's coalesce all the requested iv features or changes here. Feel free to add comments with new suggestions, and I will occasionally merge them into this list.

They are in no particular order.

-----

- [ ] **Full support of OCIO color spaces and displays**
- [ ] Dark mode (was #311)  (Suggestion: does this help? https://github.com/ColinDuquesnoy/QDarkStyleSheet
- [ ] Difference mode: shows you the absdiff between the current image and the last image. (originally #291)
- [ ] Wipe mode: There should be a mouse+modifier that splits the screen horizontally and/or vertically (depending on the mouse movement direction) of the current image and the previous image. (originally #292)
- [ ] Have iv able display partially-written exr files (originally #1191).
- [ ] Area probe: Allow a way to sweep out a rectangle and report the min/max/avg values within the rectangle. (originally #310)
- [ ] Flip and rotate should be added to the edit menu (or view?). (originally #290)
- [ ] "Save window" doesn't work -- it saves the whole image. (originally #286)
- [ ] iv Help menu should have a choice that tells you all the available plugins or formats supported (similar to `oiiotool --help`) (originally #279)

**Comment by Silverlan** [comment]
Support for the KTX-format would be great!
https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/

**Comment by lgritz** [comment]
@silverlan That's a great idea. Can you file a new issue about supporting this file format? This is not really an `iv` related issue, as this ticket is dedicated to, since iv doesn't contain any format-specific code at all (it just relies on OIIO's support for many formats).

**Comment by lgritz** [comment]
I added the KTX request on a different ticket.

**Comment by lgritz** [comment]
I marked this as "good first issue", but just to clarify -- this is a "super-issue" that lists many previously suggested improvements to iv. Any *one* of these may be a good first issue, not trying to do all of them at once, obviously.

**Comment by CheeksTheGeek** [comment]
Hi, I want to take up the task for 
"Load a directory: iv dirname ought to be the same as specifying all the image files in that directory"
which image file formats is the iv tool supposed to work with?

**Comment by CheeksTheGeek** [comment]
also, is it supposed to also work with `iv filename1 dirname` and so on?

**Comment by lgritz** [comment]
@CheeksTheGeek Yeah, I would assume that it's fine to have multiple files or directories on the command line -- for each file, it opens that image, and for each directory, it opens all the image files in that directory. (And, I should add, it should not be an error if there are files in that directory that are not image files.)

**Comment by CheeksTheGeek** [comment]
> @CheeksTheGeek Yeah, I would assume that it's fine to have multiple files or directories on the command line -- for each file, it opens that image, and for each directory, it opens all the image files in that directory. (And, I should add, it should not be an error if there are files in that directory that are not image files.)

Yupp! I had a feeling, that would be more ux intuitive, so did this, if the directory doesn't have even a single valid image, it then throws an error and continues with other files/dirs

**Comment by antond-weta** [comment]
I'd like to take the OCIO support feature. It is probably too much work for the dev day, but I could start.

**Comment by lgritz** [comment]
That would be great. If you've ever put OCIO support on a viewport before, it's probably not a big job for you.

If it simplifies things, I wouldn't mind at all if the OCIO features in `iv` only worked with OCIO >= 2.0. I think OIIO's support for OCIO 1.x will probably get dropped before next year's release, so I'm not sure I would recommend investing much time in a second code path for it with so little runway left. I'm saying all that without much appreciation for whether it's any appreciable amount of extra work to support both 1.x and 2.x. Use your best judgment and don't feel obligated to support too far back.

**Comment by kylefs1** [comment]
Hi, I'd like to take on the `"Open" shouldn't resize the window` issue for the AWSF Dev Day

**Comment by lgritz** [comment]
Bumping this issue, as it lists many small tasks that would (individually) be ideal Dev Days tasks.

**Comment by tkchanat** [comment]
I would like to work on the display and data windows overlay task #308 in DevDays 2024.

**Comment by lydia-zheng** [comment]
@lgritz Just a heads up as I'm combing through the Dev Day first issues, looks like tasklists will be deprecated next week!
Just a heads up since this will convert to raw markdown soon.
Depending on how we want to organize, the unchecked tasks might need to become sub-issues?

**Comment by lgritz** [comment]
@lydia-zheng Yeah, I think the right approach is to convert to sub-issues.

**Comment by lgritz** [comment]
I converted these all to sub-issues.

**Comment by lydia-zheng** [comment]
Was going to look into converting those myself but wasn’t sure if I had ample permissions for it, thank you so much Larry!

**Comment by lgritz** [comment]
Poking this issue so it stays in the Clotributor rotation as a potential source of Dev Days ideas. Also open to other features or quality-of-life improvements to iv, even if not listed here. Feel free to make a proposal.
